### ISSUE TITLE
approle

### ISSUE THREAD

**Issue by arthurtsang** [jpweber/vault_approle_tester#1]
hi, i'm trying to get approle to work too.  is this working or we'll need more work?  can you put some information as to what is this supposed to do?  I searched github and appears you are the only one adopting approle ATM.  Thanks.

**Comment by jpweber** [comment]
Sorry for the very late reply. This only tests that your approle configuration is working. Think of it as a test container for your vault approle configuration

However if you still have questions feel free to post them and I can try to help
